name: ScanCentral SAST Scan

on: [workflow_dispatch]

jobs:
  ScanCentral-SAST-Scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: fortify/gha-setup-scancentral-client@v2
        with:
          client-auth-token: sampleToken
      - run: scancentral -url http://microfocus.com/fortify start -bt mvn
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: scancentral-logs
          path: ~/.fortify/scancentral/log
